package com.vish.fno.util;

public enum Trend {
    WEAK_UPTREND,
    UPTREND,
    STRONG_UPTREND,
    WEAK_DOWNTREND,
    DOWNTREND,
    STRONG_DOWNTREND,
    INDECISIVE,
    SIDEWAYS,
    ACCUMULATION,
    DISTRIBUTION,
    CONSOLIDATION,
    BREAKOUT,
    REVERSAL,
}

