spring:
    mvc.pathmatch.matching-strategy: ant_path_matcher
    view:
        prefix: /static/
        suffix: .html
    main.banner-mode: off
    data.mongodb:
        host: localhost
        port: 27017
        database: fno

springdoc:
    swagger-ui:
        path: /swagger

server:
    port: 443
    ssl:
        enabled: true
        key-store-password:
        key-store:
        key-store-type: PKCS12

logging:
    level:
        root: INFO
        org.springframework.web: ERROR
        com.vish.fno: DEBUG
        okhttp3.OkHttpClient: ERROR
        com.zerodhatech: INFO
    file:
        path: logs
        name: logs/kr.log
    pattern:
        file: "%d{yyyy-MM-dd HH:mm:ss.SSSZ} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } [%8.8t] %-30.30logger{30} : %m%n"
        console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p})\
              {magenta}%clr(-){faint}%clr([%6.6t]){faint}%clr(%-30.30logger{30}){cyan} %clr(:){faint} %m%n"
    logback:
        rollingpolicy:
            max-file-size: 5MB
            file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"

# configs for actuator endpoints
management:
    server.port: 8080
    endpoint:
        info.cache.time-to-live: 5s
        health:
            show-details: always
            cache.time-to-live: 5s
        metrics.enabled: true
        prometheus.enabled: true
    endpoints.web:
        exposure.include: "*"
        base-path: /actuator
    prometheus.metrics.export:
        enabled: true
        step: 30s

strategies:
    list:
        - strategyName: Strategy1
          index: index1
          enabled: true
          expiryDayOrders: false
        - strategyName: Strategy2
          index: index2
          enabled: false

kite:
    baseuri: https://kite.trade
    apiKey:
    userId:
    apiSecret:
    liveData:
    authenticationUrl: ${kite.baseuri}/connect/login?api_key=${kite.apiKey}&v=3
    serviceInCloud: false
    holidays2023:
        - "2023-01-22"
        - "2023-01-26"
        - "2023-03-07"
        - "2023-03-30"
        - "2023-04-04"
        - "2023-04-07"
        - "2023-04-14"
        - "2023-05-01"
        - "2023-06-29"
        - "2023-08-15"
        - "2023-09-19"
        - "2023-10-02"
        - "2023-10-24"
        - "2023-11-14"
        - "2023-11-27"
        - "2023-12-25"

order:
    symbolsPath: ind_nifty100list.csv
    additionalSymbols: NIFTY, NIFTY 50, BANKNIFTY, NIFTY BANK
    webSocketDefaultSymbols: NIFTY BANK, NIFTY 50
    availableCash:
    placeOrders:
    connectToWebSocket:
